# Site settings
title: spbnick pokes tech
name: Nikolai Kondrashov
email: spbnick@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A blog about all things technology, but mostly computer software and
    hardware.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spbnick.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  spbnick
github_issues_ui: https://github.com/spbnick/spbnick.github.io/issues
github_issues_api: https://api.github.com/repos/spbnick/spbnick.github.io/issues
gplus_url: https://plus.google.com/+NikolaiKondrashov/posts

# Build settings
markdown: kramdown
